# Generated by Django 4.2.23 on 2025-07-18 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_management_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hall',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
