# Generated by Django 4.2.23 on 2025-07-18 13:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('event_management_app', '0002_hall_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='hall',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='halls', to=settings.AUTH_USER_MODEL),
        ),
    ]
