# Generated by Django 4.2.23 on 2025-07-21 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_management_app', '0003_hall_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='entry_fee',
            field=models.FloatField(default=350.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='genre',
            field=models.CharField(default='Concert', max_length=50),
            preserve_default=False,
        ),
    ]
