# Generated by Django 4.2.23 on 2025-07-22 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event_management_app', '0004_event_entry_fee_event_genre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='attendees',
        ),
    ]
