# Generated by Django 4.2.23 on 2025-07-23 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_management_app', '0005_remove_event_attendees'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='past_event',
            field=models.BooleanField(default=False),
        ),
    ]
