# Generated by Django 4.2.23 on 2025-07-17 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='otp',
            field=models.CharField(default=False, max_length=6),
        ),
        migrations.AddField(
            model_name='appuser',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
